-- ============================================
-- ADD ALL MISSING NAMES TO ons_baby_names
-- 152 names total (76 boys + 76 girls) from ONS data
-- Based on comprehensive analysis of actual 2024 rankings
-- ============================================

INSERT INTO ons_baby_names (id, name, gender, origin, meaning, cultural_category, created_at, updated_at) VALUES

-- ===== BOYS NAMES (76 names) =====
(uuid_generate_v4(), 'Adam', 'boys', 'Hebrew', 'Man, earth', 'Biblical', NOW(), NOW()),
(uuid_generate_v4(), 'Albert', 'boys', 'Germanic', 'Noble, bright', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Albie', 'boys', 'English', 'Noble, bright', 'Vintage', NOW(), NOW()),
(uuid_generate_v4(), 'Alexander', 'boys', 'Greek', 'Defender of mankind', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Alfie', 'boys', 'Anglo-Saxon', 'Wise counsellor', 'Vintage', NOW(), NOW()),
(uuid_generate_v4(), 'Alfred', 'boys', 'Anglo-Saxon', 'Wise counsellor', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Archie', 'boys', 'Germanic', 'Genuine, bold', 'Vintage', NOW(), NOW()),
(uuid_generate_v4(), 'Arlo', 'boys', 'Germanic', 'Army hill', 'Modern', NOW(), NOW()),
(uuid_generate_v4(), 'Benjamin', 'boys', 'Hebrew', 'Son of the right hand', 'Biblical', NOW(), NOW()),
(uuid_generate_v4(), 'Bobby', 'boys', 'Germanic', 'Bright fame', 'Vintage', NOW(), NOW()),
(uuid_generate_v4(), 'Caleb', 'boys', 'Hebrew', 'Whole hearted, bold', 'Biblical', NOW(), NOW()),
(uuid_generate_v4(), 'Charlie', 'boys', 'Germanic', 'Free man', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Daniel', 'boys', 'Hebrew', 'God is my judge', 'Biblical', NOW(), NOW()),
(uuid_generate_v4(), 'David', 'boys', 'Hebrew', 'Beloved', 'Biblical', NOW(), NOW()),
(uuid_generate_v4(), 'Dylan', 'boys', 'Welsh', 'Great tide', 'Celtic', NOW(), NOW()),
(uuid_generate_v4(), 'Edward', 'boys', 'Anglo-Saxon', 'Wealthy guardian', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Elijah', 'boys', 'Hebrew', 'My God is Yahweh', 'Biblical', NOW(), NOW()),
(uuid_generate_v4(), 'Elliot', 'boys', 'English', 'God on high', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Ellis', 'boys', 'Welsh', 'Benevolent', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Ethan', 'boys', 'Hebrew', 'Strong, firm', 'Biblical', NOW(), NOW()),
(uuid_generate_v4(), 'Ezra', 'boys', 'Hebrew', 'Helper', 'Biblical', NOW(), NOW()),
(uuid_generate_v4(), 'Felix', 'boys', 'Latin', 'Happy, fortunate', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Finley', 'boys', 'Scottish', 'Fair warrior', 'Celtic', NOW(), NOW()),
(uuid_generate_v4(), 'Finn', 'boys', 'Irish', 'Fair', 'Celtic', NOW(), NOW()),
(uuid_generate_v4(), 'Frankie', 'boys', 'Germanic', 'Free man', 'Vintage', NOW(), NOW()),
(uuid_generate_v4(), 'Freddie', 'boys', 'Germanic', 'Peaceful ruler', 'Vintage', NOW(), NOW()),
(uuid_generate_v4(), 'Frederick', 'boys', 'Germanic', 'Peaceful ruler', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Gabriel', 'boys', 'Hebrew', 'God is my strength', 'Biblical', NOW(), NOW()),
(uuid_generate_v4(), 'Grayson', 'boys', 'English', 'Son of the steward', 'Modern', NOW(), NOW()),
(uuid_generate_v4(), 'Harrison', 'boys', 'English', 'Son of Harry', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Harry', 'boys', 'Germanic', 'Home ruler', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Henry', 'boys', 'Germanic', 'Home ruler', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Hugo', 'boys', 'Germanic', 'Mind, intellect', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Ibrahim', 'boys', 'Arabic', 'Father of multitudes', 'Islamic', NOW(), NOW()),
(uuid_generate_v4(), 'Isaac', 'boys', 'Hebrew', 'Laughter', 'Biblical', NOW(), NOW()),
(uuid_generate_v4(), 'Jack', 'boys', 'English', 'God is gracious', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Jacob', 'boys', 'Hebrew', 'Supplanter', 'Biblical', NOW(), NOW()),
(uuid_generate_v4(), 'James', 'boys', 'Hebrew', 'Supplanter', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Jasper', 'boys', 'Persian', 'Bringer of treasure', 'Nature', NOW(), NOW()),
(uuid_generate_v4(), 'Jaxon', 'boys', 'English', 'God is gracious', 'Modern', NOW(), NOW()),
(uuid_generate_v4(), 'Jesse', 'boys', 'Hebrew', 'Gift', 'Biblical', NOW(), NOW()),
(uuid_generate_v4(), 'Joseph', 'boys', 'Hebrew', 'God will add', 'Biblical', NOW(), NOW()),
(uuid_generate_v4(), 'Joshua', 'boys', 'Hebrew', 'God is salvation', 'Biblical', NOW(), NOW()),
(uuid_generate_v4(), 'Kai', 'boys', 'Hawaiian', 'Ocean', 'Modern', NOW(), NOW()),
(uuid_generate_v4(), 'Leon', 'boys', 'Greek', 'Lion', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Liam', 'boys', 'Irish', 'Strong protector', 'Celtic', NOW(), NOW()),
(uuid_generate_v4(), 'Logan', 'boys', 'Scottish', 'Little hollow', 'Modern', NOW(), NOW()),
(uuid_generate_v4(), 'Louie', 'boys', 'Germanic', 'Famous warrior', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Louis', 'boys', 'Germanic', 'Famous warrior', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Luca', 'boys', 'Latin', 'From Lucania', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Lucas', 'boys', 'Latin', 'From Lucania', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Max', 'boys', 'Latin', 'Greatest', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Michael', 'boys', 'Hebrew', 'Who is like God', 'Biblical', NOW(), NOW()),
(uuid_generate_v4(), 'Milo', 'boys', 'Germanic', 'Mild, peaceful', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Mohammed', 'boys', 'Arabic', 'Praised', 'Islamic', NOW(), NOW()),
(uuid_generate_v4(), 'Oscar', 'boys', 'Irish', 'Divine spear', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Ralph', 'boys', 'Germanic', 'Wolf counsel', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Reggie', 'boys', 'Germanic', 'Powerful ruler', 'Vintage', NOW(), NOW()),
(uuid_generate_v4(), 'Reuben', 'boys', 'Hebrew', 'Behold, a son', 'Biblical', NOW(), NOW()),
(uuid_generate_v4(), 'Riley', 'boys', 'Irish', 'Valiant', 'Modern', NOW(), NOW()),
(uuid_generate_v4(), 'Roman', 'boys', 'Latin', 'From Rome', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Ronnie', 'boys', 'Germanic', 'Powerful ruler', 'Vintage', NOW(), NOW()),
(uuid_generate_v4(), 'Rory', 'boys', 'Irish', 'Red king', 'Celtic', NOW(), NOW()),
(uuid_generate_v4(), 'Rowan', 'boys', 'Gaelic', 'Red-haired', 'Nature', NOW(), NOW()),
(uuid_generate_v4(), 'Rupert', 'boys', 'Germanic', 'Bright fame', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Samuel', 'boys', 'Hebrew', 'Name of God', 'Biblical', NOW(), NOW()),
(uuid_generate_v4(), 'Sebastian', 'boys', 'Greek', 'Venerable', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Teddy', 'boys', 'Greek', 'Divine gift', 'Vintage', NOW(), NOW()),
(uuid_generate_v4(), 'Theo', 'boys', 'Greek', 'Divine gift', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Theodore', 'boys', 'Greek', 'Divine gift', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Thomas', 'boys', 'Aramaic', 'Twin', 'Biblical', NOW(), NOW()),
(uuid_generate_v4(), 'Toby', 'boys', 'Hebrew', 'God is good', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Tommy', 'boys', 'Aramaic', 'Twin', 'Vintage', NOW(), NOW()),
(uuid_generate_v4(), 'William', 'boys', 'Germanic', 'Resolute protector', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Yusuf', 'boys', 'Arabic', 'God increases', 'Islamic', NOW(), NOW()),
(uuid_generate_v4(), 'Zachary', 'boys', 'Hebrew', 'Remembered by God', 'Biblical', NOW(), NOW()),

-- ===== GIRLS NAMES (76 names) =====
(uuid_generate_v4(), 'Ada', 'girls', 'Germanic', 'Noble', 'Vintage', NOW(), NOW()),
(uuid_generate_v4(), 'Alice', 'girls', 'Germanic', 'Noble', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Amelie', 'girls', 'French', 'Hardworking', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Arabella', 'girls', 'Latin', 'Beautiful prayer', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Aria', 'girls', 'Italian', 'Air, melody', 'Modern', NOW(), NOW()),
(uuid_generate_v4(), 'Aurora', 'girls', 'Latin', 'Dawn', 'Mythological', NOW(), NOW()),
(uuid_generate_v4(), 'Ayla', 'girls', 'Turkish', 'Moonlight', 'Islamic', NOW(), NOW()),
(uuid_generate_v4(), 'Bella', 'girls', 'Italian', 'Beautiful', 'Modern', NOW(), NOW()),
(uuid_generate_v4(), 'Bonnie', 'girls', 'Scottish', 'Beautiful', 'Vintage', NOW(), NOW()),
(uuid_generate_v4(), 'Charlotte', 'girls', 'French', 'Free woman', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Chloe', 'girls', 'Greek', 'Young green shoot', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Clara', 'girls', 'Latin', 'Clear, bright', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Daisy', 'girls', 'English', 'Day eye', 'Nature', NOW(), NOW()),
(uuid_generate_v4(), 'Darcie', 'girls', 'Irish', 'Dark one', 'Modern', NOW(), NOW()),
(uuid_generate_v4(), 'Delilah', 'girls', 'Hebrew', 'Delicate', 'Biblical', NOW(), NOW()),
(uuid_generate_v4(), 'Eleanor', 'girls', 'Greek', 'Light', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Eliza', 'girls', 'Hebrew', 'God is my oath', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Elizabeth', 'girls', 'Hebrew', 'God is my oath', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Ella', 'girls', 'Germanic', 'All, completely', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Ellie', 'girls', 'Greek', 'Light', 'Modern', NOW(), NOW()),
(uuid_generate_v4(), 'Elsie', 'girls', 'Scottish', 'Pledged to God', 'Vintage', NOW(), NOW()),
(uuid_generate_v4(), 'Emilia', 'girls', 'Latin', 'Rival', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Emily', 'girls', 'Latin', 'Rival', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Emma', 'girls', 'Germanic', 'Universal', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Erin', 'girls', 'Irish', 'From Ireland', 'Celtic', NOW(), NOW()),
(uuid_generate_v4(), 'Esme', 'girls', 'French', 'Beloved', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Eva', 'girls', 'Hebrew', 'Living', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Evelyn', 'girls', 'English', 'Wished for child', 'Vintage', NOW(), NOW()),
(uuid_generate_v4(), 'Evie', 'girls', 'Hebrew', 'Living', 'Vintage', NOW(), NOW()),
(uuid_generate_v4(), 'Fatima', 'girls', 'Arabic', 'Captivating', 'Islamic', NOW(), NOW()),
(uuid_generate_v4(), 'Hallie', 'girls', 'English', 'Dweller at the hall', 'Modern', NOW(), NOW()),
(uuid_generate_v4(), 'Harper', 'girls', 'English', 'Harp player', 'Modern', NOW(), NOW()),
(uuid_generate_v4(), 'Harriet', 'girls', 'Germanic', 'Home ruler', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Imogen', 'girls', 'Celtic', 'Maiden', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Iris', 'girls', 'Greek', 'Rainbow', 'Nature', NOW(), NOW()),
(uuid_generate_v4(), 'Isabella', 'girls', 'Hebrew', 'God is my oath', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Isabelle', 'girls', 'Hebrew', 'God is my oath', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Jasmine', 'girls', 'Persian', 'Jasmine flower', 'Nature', NOW(), NOW()),
(uuid_generate_v4(), 'Jessica', 'girls', 'Hebrew', 'God beholds', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Lara', 'girls', 'Latin', 'Famous', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Layla', 'girls', 'Arabic', 'Night', 'Islamic', NOW(), NOW()),
(uuid_generate_v4(), 'Lola', 'girls', 'Spanish', 'Sorrows', 'Modern', NOW(), NOW()),
(uuid_generate_v4(), 'Lottie', 'girls', 'French', 'Free woman', 'Vintage', NOW(), NOW()),
(uuid_generate_v4(), 'Luna', 'girls', 'Latin', 'Moon', 'Nature', NOW(), NOW()),
(uuid_generate_v4(), 'Lyla', 'girls', 'Arabic', 'Night', 'Modern', NOW(), NOW()),
(uuid_generate_v4(), 'Lyra', 'girls', 'Greek', 'Lyre', 'Mythological', NOW(), NOW()),
(uuid_generate_v4(), 'Mabel', 'girls', 'Latin', 'Lovable', 'Vintage', NOW(), NOW()),
(uuid_generate_v4(), 'Maisie', 'girls', 'Scottish', 'Pearl', 'Vintage', NOW(), NOW()),
(uuid_generate_v4(), 'Maria', 'girls', 'Hebrew', 'Wished for child', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Matilda', 'girls', 'Germanic', 'Mighty in battle', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Maya', 'girls', 'Sanskrit', 'Illusion', 'Modern', NOW(), NOW()),
(uuid_generate_v4(), 'Mila', 'girls', 'Slavic', 'Gracious', 'Modern', NOW(), NOW()),
(uuid_generate_v4(), 'Millie', 'girls', 'Germanic', 'Gentle strength', 'Vintage', NOW(), NOW()),
(uuid_generate_v4(), 'Myla', 'girls', 'English', 'Merciful', 'Modern', NOW(), NOW()),
(uuid_generate_v4(), 'Nancy', 'girls', 'Hebrew', 'Grace', 'Vintage', NOW(), NOW()),
(uuid_generate_v4(), 'Nellie', 'girls', 'Greek', 'Light', 'Vintage', NOW(), NOW()),
(uuid_generate_v4(), 'Olive', 'girls', 'Latin', 'Olive tree', 'Nature', NOW(), NOW()),
(uuid_generate_v4(), 'Orla', 'girls', 'Irish', 'Golden princess', 'Celtic', NOW(), NOW()),
(uuid_generate_v4(), 'Penelope', 'girls', 'Greek', 'Weaver', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Phoebe', 'girls', 'Greek', 'Bright', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Robyn', 'girls', 'Germanic', 'Bright fame', 'Modern', NOW(), NOW()),
(uuid_generate_v4(), 'Rosa', 'girls', 'Latin', 'Rose', 'Nature', NOW(), NOW()),
(uuid_generate_v4(), 'Rose', 'girls', 'Latin', 'Rose flower', 'Nature', NOW(), NOW()),
(uuid_generate_v4(), 'Rosie', 'girls', 'Latin', 'Rose', 'Nature', NOW(), NOW()),
(uuid_generate_v4(), 'Ruby', 'girls', 'Latin', 'Red gemstone', 'Nature', NOW(), NOW()),
(uuid_generate_v4(), 'Sara', 'girls', 'Hebrew', 'Princess', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Scarlett', 'girls', 'English', 'Red', 'Modern', NOW(), NOW()),
(uuid_generate_v4(), 'Sienna', 'girls', 'Italian', 'Orange red', 'Modern', NOW(), NOW()),
(uuid_generate_v4(), 'Sofia', 'girls', 'Greek', 'Wisdom', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Sophia', 'girls', 'Greek', 'Wisdom', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Sophie', 'girls', 'Greek', 'Wisdom', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Thea', 'girls', 'Greek', 'Goddess', 'Classic', NOW(), NOW()),
(uuid_generate_v4(), 'Violet', 'girls', 'Latin', 'Purple flower', 'Nature', NOW(), NOW()),
(uuid_generate_v4(), 'Willow', 'girls', 'English', 'Willow tree', 'Nature', NOW(), NOW()),
(uuid_generate_v4(), 'Zara', 'girls', 'Arabic', 'Blooming flower', 'Islamic', NOW(), NOW()),
(uuid_generate_v4(), 'Zoe', 'girls', 'Greek', 'Life', 'Classic', NOW(), NOW());

-- ============================================
-- VERIFICATION
-- ============================================

-- Check total names after insertion (should be around 200)
SELECT COUNT(*) as total_names FROM ons_baby_names;

-- Check breakdown by gender
SELECT gender, COUNT(*) as count 
FROM ons_baby_names 
GROUP BY gender 
ORDER BY gender;

-- Check cultural category distribution
SELECT cultural_category, COUNT(*) as count 
FROM ons_baby_names 
GROUP BY cultural_category 
ORDER BY count DESC;
