#!/bin/bash

# Baby Steps - Stripe Setup Script (Simplified Pricing)
# This script helps you set up Stripe products and payment links

echo "========================================="
echo "Baby Steps - Stripe Product Setup Guide"
echo "========================================="
echo ""
echo "This guide will help you create the required products in Stripe."
echo ""
echo "STEP 1: Log into your Stripe Dashboard"
echo "----------------------------------------"
echo "Go to: https://dashboard.stripe.com/test/products"
echo "(Make sure you're in TEST mode - toggle at top right)"
echo ""
read -p "Press Enter when you're logged in..."

echo ""
echo "STEP 2: Create Your Products"
echo "----------------------------------------"
echo ""
echo "You need to create 2 products with Payment Links:"
echo ""
echo "Product 1: Baby Steps Premium - Monthly"
echo "  - Name: Baby Steps Premium"
echo "  - Price: £6.99/month"
echo "  - Trial period: 14 days"
echo "  - Description: Complete pregnancy planning solution with unlimited features"
echo ""
echo "Product 2: Baby Steps Premium - Annual"
echo "  - Name: Baby Steps Premium Annual"
echo "  - Price: £69.99/year (saves £14!)"
echo "  - Trial period: 14 days"
echo "  - Description: Best value - save £14 with annual billing!"
echo ""
read -p "Press Enter when you've created both products..."

echo ""
echo "STEP 3: Create Payment Links"
echo "----------------------------------------"
echo ""
echo "For EACH product:"
echo "1. Click on the product"
echo "2. Click 'Create payment link'"
echo "3. Settings to use:"
echo "   - Quantity: Customer chooses (OFF)"
echo "   - Collect customer details: Email (Required)"
echo "   - After payment: Show confirmation page"
echo "   - Customer portal: Enable"
echo "4. Click 'Create link'"
echo "5. Copy the payment link URL"
echo ""
read -p "Press Enter when you've created both payment links..."

echo ""
echo "STEP 4: Update Your .env File"
echo "----------------------------------------"
echo ""
echo "Add these to your .env file:"
echo ""
echo "REACT_APP_STRIPE_MONTHLY_URL=[Your monthly payment link]"
echo "REACT_APP_STRIPE_ANNUAL_URL=[Your annual payment link]"
echo ""
echo "Example format:"
echo "REACT_APP_STRIPE_MONTHLY_URL=https://buy.stripe.com/test_abc123xyz"
echo ""
read -p "Press Enter when you've updated your .env file..."

echo ""
echo "STEP 5: Set Up Webhooks (For Production)"
echo "----------------------------------------"
echo ""
echo "1. Go to: https://dashboard.stripe.com/test/webhooks"
echo "2. Click 'Add endpoint'"
echo "3. Endpoint URL: https://your-domain.com/api/stripe-webhook"
echo "4. Events to listen for:"
echo "   - customer.subscription.created"
echo "   - customer.subscription.updated"
echo "   - customer.subscription.deleted"
echo "   - checkout.session.completed"
echo "5. Copy the webhook signing secret"
echo ""
echo "Note: Webhooks are for production. For testing, payment links work without them."
echo ""
read -p "Press Enter to continue..."

echo ""
echo "STEP 6: Test Your Integration"
echo "----------------------------------------"
echo ""
echo "1. Restart your React app: npm start"
echo "2. Create a new test account"
echo "3. Try to add more than 10 shopping items"
echo "4. You should see the paywall modal"
echo "5. Click upgrade and test with Stripe test card: 4242 4242 4242 4242"
echo ""
echo "Test card details:"
echo "  Number: 4242 4242 4242 4242"
echo "  Expiry: Any future date"
echo "  CVC: Any 3 digits"
echo "  ZIP: Any 5 digits"
echo ""
echo "========================================="
echo "Setup Complete!"
echo "========================================="
echo ""
echo "Your paywall is ready to test!"
echo ""
echo "Pricing:"
echo "- Monthly: £6.99/month"
echo "- Annual: £69.99/year (saves £14)"
echo ""
echo "Remember:"
echo "- You're in TEST mode - no real charges"
echo "- Your 4 VIP users already have lifetime access"
echo "- Other existing users have 30-day grace period"
echo "- New users get 14-day trial"
echo ""
echo "For production:"
echo "1. Switch Stripe to LIVE mode"
echo "2. Create real products with real prices"
echo "3. Update .env with live keys and URLs"
echo "4. Deploy to production"
echo ""
