name = "uptheduff"
compatibility_date = "2025-06-04"

[assets]
directory = "./build"

[[assets.redirects]]
from = "/signup*"
to = "/index.html"
status = 200

[[assets.redirects]]
from = "/blog*"
to = "/index.html"
status = 200

[[assets.redirects]]
from = "/with/*"
to = "/index.html"
status = 200

[[assets.redirects]]
from = "/influencer/*"
to = "/index.html"
status = 200

[[assets.redirects]]
from = "/privacy-policy"
to = "/index.html"
status = 200

[[assets.redirects]]
from = "/terms-of-service"
to = "/index.html"
status = 200

[[assets.redirects]]
from = "/reset-password"
to = "/index.html"
status = 200

[[assets.redirects]]
from = "/subscription*"
to = "/index.html"
status = 200

[[assets.redirects]]
from = "/debug-auth"
to = "/index.html"
status = 200

[[assets.redirects]]
from = "/influencer-signup"
to = "/index.html"
status = 200